# Generated by Django 4.1.3 on 2022-12-25 01:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="likers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
