# Generated by Django 4.1.3 on 2022-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_list",
            name="category",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="auction_list",
            name="url_image",
            field=models.URLField(default=""),
        ),
    ]
