# Generated by Django 4.1.3 on 2022-12-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_watchlist_items_remove_watchlist_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_item",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
