# Generated by Django 4.1.3 on 2022-12-12 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_item_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_item",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
