# Generated by Django 4.1.3 on 2022-12-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auction_list_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auction_list",
            new_name="Auction_item",
        ),
    ]
