# Generated by Django 4.1.3 on 2022-12-12 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_item_watchers_delete_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_item",
            name="user_id",
        ),
        migrations.AddField(
            model_name="auction_item",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
